version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=mamedov'
      - 'POSTGRES_PASSWORD=mamedov'
      - 'POSTGRES_DB=students'


  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
    links:
      - 'postgres:database'